
server:
  port: 9120

spring:
  application:
    name: election-vote

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9080/eureka/

############################### mybatis-plus start #################################
mybatis-plus:
  # 启动时是否检查MyBatis XML文件是否存在
  check-config-location: true
  # 支持统配符 * 或者 ; 分割
  # MyBatis原生配置
  configuration:
    # 字段名称下划线转驼峰命名
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 全局默认主键类型
      id-type: auto
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
  # mapper xml映射路径
  mapper-locations: classpath*:mapper/**/*Mapper.xml
################################ mybatis-plus end ##################################

############################### Redis 公共配置 start ###############################
---
spring:
  redis:
    timeout: 10s
    lettuce:
      pool:
        max-active: 200
        max-idle: 8
        max-wait: 10s
        min-idle: 2
      shutdown-timeout: 3s
############################### Redis 公共配置 end ##################################

############################### HikariCP 数据源配置 start ################################
---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    cachePrepStmts: true
    prepStmtCacheSize: 300
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
    useLocalSessionState: true
    rewriteBatchedStatements: true
    cacheResultSetMetadata: true
    cacheServerConfiguration: true
    elideSetAutoCommits: true
    maintainTimeStats: false
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 10000
      max-lifetime: 1800000
      connection-timeout: 30000
############################### HikariCP 数据源配置 end ################################

############################### mysql & redis 配置 start ###############################
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/election_vote?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ABCabc123

  # Redis配置
  redis:
    database: 2
    host: localhost
    password: sa!2fdiEs
    port: 6379
############################### mysql & redis 配置 end ###############################

#################################### Swagger start #################################
---
vote:
  swagger:
    # 是否启用
    enable: true
    base:
      # 扫描的包，多个包使用逗号隔开
      package: test.ivan.vote
    contact:
      email: ivan@moeec.com
      name: vote
      url: http://#
    description:
    title: ${spring.application.name} API Documents
    url: http://#
    version: ${project.version}
    # 自定义参数配置，可配置N个
    parameter-config:
      - name: token
        description: Token Request Header
        # header, cookie, body, query
        type: header
        data-type: String
        required: false
        # 测试接口时，自动填充token的值
        default-value:

# knife4j配置
knife4j:
  enable: ${vote.swagger.enable}
  basic:
    enable: true
    username: admin
    password: admin

#################################### Swagger end ###################################